//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.15 at 10:45:46 AM MSK 
//


package by.it.shkantau.jd02.jd02_09.airport;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flights">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="flight" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="plane" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="departureTime" type="{http://airport.jd02_09.jd02.shkantau.it.by}DateTime"/>
 *                             &lt;element name="arrivalTime" type="{http://airport.jd02_09.jd02.shkantau.it.by}DateTime"/>
 *                             &lt;element name="crew">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;all>
 *                                       &lt;element name="pilots">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="pilot" maxOccurs="2">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;all>
 *                                                           &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
 *                                                           &lt;element name="phone" type="{http://airport.jd02_09.jd02.shkantau.it.by}Phone"/>
 *                                                         &lt;/all>
 *                                                         &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="airHostesses">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="airHostess" maxOccurs="2">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;all>
 *                                                           &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
 *                                                         &lt;/all>
 *                                                         &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/all>
 *                                     &lt;attribute name="crewID" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                                     &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="flightID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                           &lt;attribute name="form" type="{http://airport.jd02_09.jd02.shkantau.it.by}Acronym" />
 *                           &lt;attribute name="to" type="{http://airport.jd02_09.jd02.shkantau.it.by}Acronym" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flights"
})
@XmlRootElement(name = "airport")
public class Airport {

    @XmlElement(required = true)
    protected Airport.Flights flights;

    /**
     * Gets the value of the flights property.
     * 
     * @return
     *     possible object is
     *     {@link Airport.Flights }
     *     
     */
    public Airport.Flights getFlights() {
        return flights;
    }

    /**
     * Sets the value of the flights property.
     * 
     * @param value
     *     allowed object is
     *     {@link Airport.Flights }
     *     
     */
    public void setFlights(Airport.Flights value) {
        this.flights = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="flight" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="plane" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="departureTime" type="{http://airport.jd02_09.jd02.shkantau.it.by}DateTime"/>
     *                   &lt;element name="arrivalTime" type="{http://airport.jd02_09.jd02.shkantau.it.by}DateTime"/>
     *                   &lt;element name="crew">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element name="pilots">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="pilot" maxOccurs="2">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;all>
     *                                                 &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
     *                                                 &lt;element name="phone" type="{http://airport.jd02_09.jd02.shkantau.it.by}Phone"/>
     *                                               &lt;/all>
     *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="airHostesses">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="airHostess" maxOccurs="2">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;all>
     *                                                 &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
     *                                               &lt;/all>
     *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/all>
     *                           &lt;attribute name="crewID" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                           &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="flightID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *                 &lt;attribute name="form" type="{http://airport.jd02_09.jd02.shkantau.it.by}Acronym" />
     *                 &lt;attribute name="to" type="{http://airport.jd02_09.jd02.shkantau.it.by}Acronym" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "flight"
    })
    public static class Flights {

        @XmlElement(required = true)
        protected List<Airport.Flights.Flight> flight;

        /**
         * Gets the value of the flight property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the flight property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFlight().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Airport.Flights.Flight }
         * 
         * 
         */
        public List<Airport.Flights.Flight> getFlight() {
            if (flight == null) {
                flight = new ArrayList<Airport.Flights.Flight>();
            }
            return this.flight;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="plane" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="departureTime" type="{http://airport.jd02_09.jd02.shkantau.it.by}DateTime"/>
         *         &lt;element name="arrivalTime" type="{http://airport.jd02_09.jd02.shkantau.it.by}DateTime"/>
         *         &lt;element name="crew">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element name="pilots">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="pilot" maxOccurs="2">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;all>
         *                                       &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
         *                                       &lt;element name="phone" type="{http://airport.jd02_09.jd02.shkantau.it.by}Phone"/>
         *                                     &lt;/all>
         *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="airHostesses">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="airHostess" maxOccurs="2">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;all>
         *                                       &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
         *                                     &lt;/all>
         *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/all>
         *                 &lt;attribute name="crewID" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *                 &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="flightID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *       &lt;attribute name="form" type="{http://airport.jd02_09.jd02.shkantau.it.by}Acronym" />
         *       &lt;attribute name="to" type="{http://airport.jd02_09.jd02.shkantau.it.by}Acronym" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "company",
            "plane",
            "departureTime",
            "arrivalTime",
            "crew"
        })
        public static class Flight {

            @XmlElement(required = true)
            protected String company;
            @XmlElement(required = true)
            protected Object plane;
            @XmlElement(required = true)
            protected String departureTime;
            @XmlElement(required = true)
            protected String arrivalTime;
            @XmlElement(required = true)
            protected Airport.Flights.Flight.Crew crew;
            @XmlAttribute(name = "flightID", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String flightID;
            @XmlAttribute(name = "form")
            protected String form;
            @XmlAttribute(name = "to")
            protected String to;

            /**
             * Gets the value of the company property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCompany() {
                return company;
            }

            /**
             * Sets the value of the company property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCompany(String value) {
                this.company = value;
            }

            /**
             * Gets the value of the plane property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getPlane() {
                return plane;
            }

            /**
             * Sets the value of the plane property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setPlane(Object value) {
                this.plane = value;
            }

            /**
             * Gets the value of the departureTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDepartureTime() {
                return departureTime;
            }

            /**
             * Sets the value of the departureTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDepartureTime(String value) {
                this.departureTime = value;
            }

            /**
             * Gets the value of the arrivalTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getArrivalTime() {
                return arrivalTime;
            }

            /**
             * Sets the value of the arrivalTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArrivalTime(String value) {
                this.arrivalTime = value;
            }

            /**
             * Gets the value of the crew property.
             * 
             * @return
             *     possible object is
             *     {@link Airport.Flights.Flight.Crew }
             *     
             */
            public Airport.Flights.Flight.Crew getCrew() {
                return crew;
            }

            /**
             * Sets the value of the crew property.
             * 
             * @param value
             *     allowed object is
             *     {@link Airport.Flights.Flight.Crew }
             *     
             */
            public void setCrew(Airport.Flights.Flight.Crew value) {
                this.crew = value;
            }

            /**
             * Gets the value of the flightID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFlightID() {
                return flightID;
            }

            /**
             * Sets the value of the flightID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFlightID(String value) {
                this.flightID = value;
            }

            /**
             * Gets the value of the form property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getForm() {
                return form;
            }

            /**
             * Sets the value of the form property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setForm(String value) {
                this.form = value;
            }

            /**
             * Gets the value of the to property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTo() {
                return to;
            }

            /**
             * Sets the value of the to property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTo(String value) {
                this.to = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element name="pilots">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="pilot" maxOccurs="2">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;all>
             *                             &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
             *                             &lt;element name="phone" type="{http://airport.jd02_09.jd02.shkantau.it.by}Phone"/>
             *                           &lt;/all>
             *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="airHostesses">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="airHostess" maxOccurs="2">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;all>
             *                             &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
             *                           &lt;/all>
             *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/all>
             *       &lt;attribute name="crewID" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
             *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}integer" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class Crew {

                @XmlElement(required = true)
                protected Airport.Flights.Flight.Crew.Pilots pilots;
                @XmlElement(required = true)
                protected Airport.Flights.Flight.Crew.AirHostesses airHostesses;
                @XmlAttribute(name = "crewID", required = true)
                @XmlSchemaType(name = "positiveInteger")
                protected BigInteger crewID;
                @XmlAttribute(name = "count")
                protected BigInteger count;

                /**
                 * Gets the value of the pilots property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Airport.Flights.Flight.Crew.Pilots }
                 *     
                 */
                public Airport.Flights.Flight.Crew.Pilots getPilots() {
                    return pilots;
                }

                /**
                 * Sets the value of the pilots property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Airport.Flights.Flight.Crew.Pilots }
                 *     
                 */
                public void setPilots(Airport.Flights.Flight.Crew.Pilots value) {
                    this.pilots = value;
                }

                /**
                 * Gets the value of the airHostesses property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Airport.Flights.Flight.Crew.AirHostesses }
                 *     
                 */
                public Airport.Flights.Flight.Crew.AirHostesses getAirHostesses() {
                    return airHostesses;
                }

                /**
                 * Sets the value of the airHostesses property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Airport.Flights.Flight.Crew.AirHostesses }
                 *     
                 */
                public void setAirHostesses(Airport.Flights.Flight.Crew.AirHostesses value) {
                    this.airHostesses = value;
                }

                /**
                 * Gets the value of the crewID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getCrewID() {
                    return crewID;
                }

                /**
                 * Sets the value of the crewID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setCrewID(BigInteger value) {
                    this.crewID = value;
                }

                /**
                 * Gets the value of the count property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getCount() {
                    return count;
                }

                /**
                 * Sets the value of the count property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setCount(BigInteger value) {
                    this.count = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="airHostess" maxOccurs="2">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;all>
                 *                   &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
                 *                 &lt;/all>
                 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "airHostess"
                })
                public static class AirHostesses {

                    @XmlElement(required = true)
                    protected List<Airport.Flights.Flight.Crew.AirHostesses.AirHostess> airHostess;

                    /**
                     * Gets the value of the airHostess property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the airHostess property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getAirHostess().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Airport.Flights.Flight.Crew.AirHostesses.AirHostess }
                     * 
                     * 
                     */
                    public List<Airport.Flights.Flight.Crew.AirHostesses.AirHostess> getAirHostess() {
                        if (airHostess == null) {
                            airHostess = new ArrayList<Airport.Flights.Flight.Crew.AirHostesses.AirHostess>();
                        }
                        return this.airHostess;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;all>
                     *         &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
                     *       &lt;/all>
                     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {

                    })
                    public static class AirHostess {

                        @XmlElement(required = true)
                        @XmlSchemaType(name = "positiveInteger")
                        protected BigInteger age;
                        @XmlAttribute(name = "name")
                        @XmlSchemaType(name = "anySimpleType")
                        protected String name;

                        /**
                         * Gets the value of the age property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link BigInteger }
                         *     
                         */
                        public BigInteger getAge() {
                            return age;
                        }

                        /**
                         * Sets the value of the age property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link BigInteger }
                         *     
                         */
                        public void setAge(BigInteger value) {
                            this.age = value;
                        }

                        /**
                         * Gets the value of the name property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getName() {
                            return name;
                        }

                        /**
                         * Sets the value of the name property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setName(String value) {
                            this.name = value;
                        }

                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="pilot" maxOccurs="2">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;all>
                 *                   &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
                 *                   &lt;element name="phone" type="{http://airport.jd02_09.jd02.shkantau.it.by}Phone"/>
                 *                 &lt;/all>
                 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "pilot"
                })
                public static class Pilots {

                    @XmlElement(required = true)
                    protected List<Airport.Flights.Flight.Crew.Pilots.Pilot> pilot;

                    /**
                     * Gets the value of the pilot property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the pilot property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getPilot().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Airport.Flights.Flight.Crew.Pilots.Pilot }
                     * 
                     * 
                     */
                    public List<Airport.Flights.Flight.Crew.Pilots.Pilot> getPilot() {
                        if (pilot == null) {
                            pilot = new ArrayList<Airport.Flights.Flight.Crew.Pilots.Pilot>();
                        }
                        return this.pilot;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;all>
                     *         &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
                     *         &lt;element name="phone" type="{http://airport.jd02_09.jd02.shkantau.it.by}Phone"/>
                     *       &lt;/all>
                     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {

                    })
                    public static class Pilot {

                        @XmlElement(required = true)
                        @XmlSchemaType(name = "positiveInteger")
                        protected BigInteger age;
                        @XmlElement(required = true)
                        protected String phone;
                        @XmlAttribute(name = "name")
                        @XmlSchemaType(name = "anySimpleType")
                        protected String name;

                        /**
                         * Gets the value of the age property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link BigInteger }
                         *     
                         */
                        public BigInteger getAge() {
                            return age;
                        }

                        /**
                         * Sets the value of the age property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link BigInteger }
                         *     
                         */
                        public void setAge(BigInteger value) {
                            this.age = value;
                        }

                        /**
                         * Gets the value of the phone property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getPhone() {
                            return phone;
                        }

                        /**
                         * Sets the value of the phone property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setPhone(String value) {
                            this.phone = value;
                        }

                        /**
                         * Gets the value of the name property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getName() {
                            return name;
                        }

                        /**
                         * Sets the value of the name property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setName(String value) {
                            this.name = value;
                        }

                    }

                }

            }

        }

    }

}
