//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.15 at 10:45:46 AM MSK 
//


package by.it.shkantau.jd02.jd02_09.airport;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.it.shkantau.jd02.jd02_09.airport package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.it.shkantau.jd02.jd02_09.airport
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Airport }
     * 
     */
    public Airport createAirport() {
        return new Airport();
    }

    /**
     * Create an instance of {@link Airport.Flights }
     * 
     */
    public Airport.Flights createAirportFlights() {
        return new Airport.Flights();
    }

    /**
     * Create an instance of {@link Airport.Flights.Flight }
     * 
     */
    public Airport.Flights.Flight createAirportFlightsFlight() {
        return new Airport.Flights.Flight();
    }

    /**
     * Create an instance of {@link Airport.Flights.Flight.Crew }
     * 
     */
    public Airport.Flights.Flight.Crew createAirportFlightsFlightCrew() {
        return new Airport.Flights.Flight.Crew();
    }

    /**
     * Create an instance of {@link Airport.Flights.Flight.Crew.AirHostesses }
     * 
     */
    public Airport.Flights.Flight.Crew.AirHostesses createAirportFlightsFlightCrewAirHostesses() {
        return new Airport.Flights.Flight.Crew.AirHostesses();
    }

    /**
     * Create an instance of {@link Airport.Flights.Flight.Crew.Pilots }
     * 
     */
    public Airport.Flights.Flight.Crew.Pilots createAirportFlightsFlightCrewPilots() {
        return new Airport.Flights.Flight.Crew.Pilots();
    }

    /**
     * Create an instance of {@link Airport.Flights.Flight.Crew.AirHostesses.AirHostess }
     * 
     */
    public Airport.Flights.Flight.Crew.AirHostesses.AirHostess createAirportFlightsFlightCrewAirHostessesAirHostess() {
        return new Airport.Flights.Flight.Crew.AirHostesses.AirHostess();
    }

    /**
     * Create an instance of {@link Airport.Flights.Flight.Crew.Pilots.Pilot }
     * 
     */
    public Airport.Flights.Flight.Crew.Pilots.Pilot createAirportFlightsFlightCrewPilotsPilot() {
        return new Airport.Flights.Flight.Crew.Pilots.Pilot();
    }

}
