//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.18 at 10:18:28 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://company.com/JD02_07", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.company.jd_07;
