//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.15 at 03:07:29 PM GMT+03:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jd02_09.jd02.prymshyts.it.by", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.prymshyts.jd02.jd02_09.auto_pojo;
