//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.15 at 11:50:33 PM AST 
//


package by.it.shkantau.jd02.jd02_09.generatedAirport;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flights">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="flight" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="plane" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="departureTime" type="{http://airport.jd02_09.jd02.shkantau.it.by}DateTime"/>
 *                             &lt;element name="arrivalTime" type="{http://airport.jd02_09.jd02.shkantau.it.by}DateTime"/>
 *                             &lt;element name="crew" type="{http://airport.jd02_09.jd02.shkantau.it.by}Crew"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="flightID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                           &lt;attribute name="form" type="{http://airport.jd02_09.jd02.shkantau.it.by}Acronym" />
 *                           &lt;attribute name="to" type="{http://airport.jd02_09.jd02.shkantau.it.by}Acronym" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flights"
})
@XmlRootElement(name = "airport")
public class Airport {

    @XmlElement(required = true)
    protected Airport.Flights flights;

    /**
     * Gets the value of the flights property.
     * 
     * @return
     *     possible object is
     *     {@link Airport.Flights }
     *     
     */
    public Airport.Flights getFlights() {
        return flights;
    }

    /**
     * Sets the value of the flights property.
     * 
     * @param value
     *     allowed object is
     *     {@link Airport.Flights }
     *     
     */
    public void setFlights(Airport.Flights value) {
        this.flights = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="flight" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="plane" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="departureTime" type="{http://airport.jd02_09.jd02.shkantau.it.by}DateTime"/>
     *                   &lt;element name="arrivalTime" type="{http://airport.jd02_09.jd02.shkantau.it.by}DateTime"/>
     *                   &lt;element name="crew" type="{http://airport.jd02_09.jd02.shkantau.it.by}Crew"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="flightID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *                 &lt;attribute name="form" type="{http://airport.jd02_09.jd02.shkantau.it.by}Acronym" />
     *                 &lt;attribute name="to" type="{http://airport.jd02_09.jd02.shkantau.it.by}Acronym" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "flight"
    })
    public static class Flights {

        @XmlElement(required = true)
        protected List<Airport.Flights.Flight> flight;

        /**
         * Gets the value of the flight property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the flight property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFlight().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Airport.Flights.Flight }
         * 
         * 
         */
        public List<Airport.Flights.Flight> getFlight() {
            if (flight == null) {
                flight = new ArrayList<>();
            }
            return this.flight;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="plane" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="departureTime" type="{http://airport.jd02_09.jd02.shkantau.it.by}DateTime"/>
         *         &lt;element name="arrivalTime" type="{http://airport.jd02_09.jd02.shkantau.it.by}DateTime"/>
         *         &lt;element name="crew" type="{http://airport.jd02_09.jd02.shkantau.it.by}Crew"/>
         *       &lt;/sequence>
         *       &lt;attribute name="flightID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *       &lt;attribute name="form" type="{http://airport.jd02_09.jd02.shkantau.it.by}Acronym" />
         *       &lt;attribute name="to" type="{http://airport.jd02_09.jd02.shkantau.it.by}Acronym" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "company",
            "plane",
            "departureTime",
            "arrivalTime",
            "crew"
        })
        public static class Flight {

            @XmlElement(required = true)
            protected String company;
            @XmlElement(required = true)
            protected Object plane;
            @XmlElement(required = true)
            protected String departureTime;
            @XmlElement(required = true)
            protected String arrivalTime;
            @XmlElement(required = true)
            protected Crew crew;
            @XmlAttribute(name = "flightID", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String flightID;
            @XmlAttribute(name = "form")
            protected String form;
            @XmlAttribute(name = "to")
            protected String to;

            /**
             * Gets the value of the company property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCompany() {
                return company;
            }

            /**
             * Sets the value of the company property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCompany(String value) {
                this.company = value;
            }

            /**
             * Gets the value of the plane property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getPlane() {
                return plane;
            }

            /**
             * Sets the value of the plane property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setPlane(Object value) {
                this.plane = value;
            }

            /**
             * Gets the value of the departureTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDepartureTime() {
                return departureTime;
            }

            /**
             * Sets the value of the departureTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDepartureTime(String value) {
                this.departureTime = value;
            }

            /**
             * Gets the value of the arrivalTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getArrivalTime() {
                return arrivalTime;
            }

            /**
             * Sets the value of the arrivalTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArrivalTime(String value) {
                this.arrivalTime = value;
            }

            /**
             * Gets the value of the crew property.
             * 
             * @return
             *     possible object is
             *     {@link Crew }
             *     
             */
            public Crew getCrew() {
                return crew;
            }

            /**
             * Sets the value of the crew property.
             * 
             * @param value
             *     allowed object is
             *     {@link Crew }
             *     
             */
            public void setCrew(Crew value) {
                this.crew = value;
            }

            /**
             * Gets the value of the flightID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFlightID() {
                return flightID;
            }

            /**
             * Sets the value of the flightID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFlightID(String value) {
                this.flightID = value;
            }

            /**
             * Gets the value of the form property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getForm() {
                return form;
            }

            /**
             * Sets the value of the form property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setForm(String value) {
                this.form = value;
            }

            /**
             * Gets the value of the to property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTo() {
                return to;
            }

            /**
             * Sets the value of the to property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTo(String value) {
                this.to = value;
            }

        }

    }

}
