//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.15 at 11:50:33 PM AST 
//


package by.it.shkantau.jd02.jd02_09.generatedAirport;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Crew complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Crew">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="pilots">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pilot" maxOccurs="2">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
 *                             &lt;element name="phone" type="{http://airport.jd02_09.jd02.shkantau.it.by}Phone"/>
 *                           &lt;/all>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="airHostesses">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="airHostess" maxOccurs="2">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
 *                           &lt;/all>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="crewID" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Crew", propOrder = {

})
public class Crew {

    @XmlElement(required = true)
    protected Crew.Pilots pilots;
    @XmlElement(required = true)
    protected Crew.AirHostesses airHostesses;
    @XmlAttribute(name = "crewID", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger crewID;
    @XmlAttribute(name = "count")
    protected BigInteger count;

    /**
     * Gets the value of the pilots property.
     * 
     * @return
     *     possible object is
     *     {@link Crew.Pilots }
     *     
     */
    public Crew.Pilots getPilots() {
        return pilots;
    }

    /**
     * Sets the value of the pilots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Crew.Pilots }
     *     
     */
    public void setPilots(Crew.Pilots value) {
        this.pilots = value;
    }

    /**
     * Gets the value of the airHostesses property.
     * 
     * @return
     *     possible object is
     *     {@link Crew.AirHostesses }
     *     
     */
    public Crew.AirHostesses getAirHostesses() {
        return airHostesses;
    }

    /**
     * Sets the value of the airHostesses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Crew.AirHostesses }
     *     
     */
    public void setAirHostesses(Crew.AirHostesses value) {
        this.airHostesses = value;
    }

    /**
     * Gets the value of the crewID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCrewID() {
        return crewID;
    }

    /**
     * Sets the value of the crewID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCrewID(BigInteger value) {
        this.crewID = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCount(BigInteger value) {
        this.count = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="airHostess" maxOccurs="2">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
     *                 &lt;/all>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "airHostess"
    })
    public static class AirHostesses {

        @XmlElement(required = true)
        protected List<Crew.AirHostesses.AirHostess> airHostess;

        /**
         * Gets the value of the airHostess property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the airHostess property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAirHostess().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Crew.AirHostesses.AirHostess }
         * 
         * 
         */
        public List<Crew.AirHostesses.AirHostess> getAirHostess() {
            if (airHostess == null) {
                airHostess = new ArrayList<Crew.AirHostesses.AirHostess>();
            }
            return this.airHostess;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
         *       &lt;/all>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class AirHostess {

            @XmlElement(required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger age;
            @XmlAttribute(name = "name")
            @XmlSchemaType(name = "anySimpleType")
            protected String name;

            /**
             * Gets the value of the age property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getAge() {
                return age;
            }

            /**
             * Sets the value of the age property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setAge(BigInteger value) {
                this.age = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pilot" maxOccurs="2">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
     *                   &lt;element name="phone" type="{http://airport.jd02_09.jd02.shkantau.it.by}Phone"/>
     *                 &lt;/all>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pilot"
    })
    public static class Pilots {

        @XmlElement(required = true)
        protected List<Crew.Pilots.Pilot> pilot;

        /**
         * Gets the value of the pilot property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pilot property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPilot().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Crew.Pilots.Pilot }
         * 
         * 
         */
        public List<Crew.Pilots.Pilot> getPilot() {
            if (pilot == null) {
                pilot = new ArrayList<Crew.Pilots.Pilot>();
            }
            return this.pilot;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="age" type="{http://airport.jd02_09.jd02.shkantau.it.by}Age"/>
         *         &lt;element name="phone" type="{http://airport.jd02_09.jd02.shkantau.it.by}Phone"/>
         *       &lt;/all>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Pilot {

            @XmlElement(required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger age;
            @XmlElement(required = true)
            protected String phone;
            @XmlAttribute(name = "name")
            @XmlSchemaType(name = "anySimpleType")
            protected String name;

            /**
             * Gets the value of the age property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getAge() {
                return age;
            }

            /**
             * Sets the value of the age property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setAge(BigInteger value) {
                this.age = value;
            }

            /**
             * Gets the value of the phone property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPhone() {
                return phone;
            }

            /**
             * Sets the value of the phone property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPhone(String value) {
                this.phone = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }

}
