//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.15 at 11:50:33 PM AST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://airport.jd02_09.jd02.shkantau.it.by", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.shkantau.jd02.jd02_09.generatedAirport;
