//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.16 at 11:48:19 AM EEST 
//


package by.it.aborisenok.JD02_09.TaskB;



import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="policlinic" type="{http://TaskC.JD02_09.aborisenok.it.by/}policlinic"/>
 *         &lt;element name="visitDate" type="{http://TaskC.JD02_09.aborisenok.it.by/}visitDate"/>
 *         &lt;element name="patient" type="{http://TaskC.JD02_09.aborisenok.it.by/}patient"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "policlinic",
    "visitDate",
    "patient"
})
@XmlRootElement(name = "ticket")
public class Ticket {

    @XmlElement(required = true)
    protected Policlinic policlinic;
    @XmlElement(required = true)
    protected VisitDate visitDate;
    @XmlElement(required = true)
    protected Patient patient;

    /**
     * Gets the value of the policlinic property.
     *
     * @return
     *     possible object is
     *     {@link Policlinic }
     *
     */
    public Policlinic getPoliclinic() {
        return policlinic;
    }

    /**
     * Sets the value of the policlinic property.
     *
     * @param value
     *     allowed object is
     *     {@link Policlinic }
     *
     */
    public void setPoliclinic(Policlinic value) {
        this.policlinic = value;
    }

    /**
     * Gets the value of the visitDate property.
     *
     * @return
     *     possible object is
     *     {@link VisitDate }
     *
     */
    public VisitDate getVisitDate() {
        return visitDate;
    }

    /**
     * Sets the value of the visitDate property.
     *
     * @param value
     *     allowed object is
     *     {@link VisitDate }
     *
     */
    public void setVisitDate(VisitDate value) {
        this.visitDate = value;
    }

    /**
     * Gets the value of the patient property.
     *
     * @return
     *     possible object is
     *     {@link Patient }
     *
     */
    public Patient getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     *
     * @param value
     *     allowed object is
     *     {@link Patient }
     *     
     */
    public void setPatient(Patient value) {
        this.patient = value;
    }

}
